
import nike001 from "../images/nike001.png";
import nike002 from "../images/nike002.png";
import nike003 from "../images/nike003.png";

const productStore = [
  {
    title: "Nike Shoes",
    brand: "Nike",
    category: "Sneakers",
    sex: "Male",
    price: 59,
    salePrice: 29,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
      { status: false, size: 42 },
      { status: false, size: 43 },
      { status: false, size: 44 },
      { status: false, size: 45 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes2",
    brand: "Nike",
    category: "Sneakers",
    sex: "Male",
    price: 45,
    salePrice: 25,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes3",
    brand: "Nike",
    category: "Sneakers",
    sex: "FemFemle",
    price: 79,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes4",
    brand: "Nike",
    category: "Sneakers",
    sex: "Male",
    price: 39,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes5",
    brand: "Nike",
    category: "Sneakers",
    sex: "Female",
    price: 109,
    salePrice: 59,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes6",
    brand: "Nike",
    category: "Running shoes",
    sex: "Male",
    price: 55,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes7",
    brand: "Nike",
    category: "Running shoes",
    sex: "Male",
    price: 65,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes8",
    brand: "Nike",
    category: "Running shoes",
    sex: "Male",
    price: 77,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Nike Shoes9",
    brand: "Nike",
    category: "Running shoes",
    sex: "Female",
    price: 99,
    salePrice: 69,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Adidas1",
    brand: "Adidas",
    category: "Winter footwear",
    sex: "Male",
    price: 49,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Adidas2",
    brand: "Adidas",
    category: "Winter footwear",
    sex: "Female",
    price: 49,
    salePrice: 39,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Adidas3",
    brand: "Adidas",
    category: "Winter footwear",
    sex: "Male",
    price: 55,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Adidas4",
    brand: "Adidas",
    category: "Winter footwear",
    sex: "Male",
    price: 65,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Adidas5",
    brand: "Adidas",
    category: "Demi-season",
    sex: "Female",
    price: 49,
    salePrice: 29,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Puma1",
    brand: "Puma",
    category: "Demi-season",
    sex: "Male",
    price: 49,
    salePrice: 25,
    endPrice: null,
    sale: true,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Puma2",
    brand: "Puma",
    category: "Demi-season",
    sex: "Male",
    price: 59,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Puma3",
    brand: "Puma",
    category: "Demi-season",
    sex: "Male",
    price: 69,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Puma4",
    brand: "Puma",
    category: "Demi-season",
    sex: "Male",
    price: 69,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "Puma5",
    brand: "Puma",
    category: "Trainers",
    sex: "Male",
    price: 59,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "New Balance1",
    brand: "New Balance",
    category: "Trainers",
    sex: "Male",
    price: 59,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
  {
    title: "New Balance2",
    brand: "New Balance",
    category: "Trainers",
    sex: "Male",
    price: 69,
    salePrice: 25,
    endPrice: null,
    sale: false,
    images: [nike001, nike002, nike003],
    sizes: [
      { status: false, size: 40 },
      { status: false, size: 41 },
    ],
    colors: [
      { status: false, color: "darkblue", id: 0 },
      { status: false, color: "black", id: 1 },
      { status: false, color: "white", id: 2 },
    ],
  },
];

export { productStore };
